# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eea7aa9c23eb334ade1851dc8e9fba1412b25c24efc5efa27b0f49dd0337da6e7a4d70fdf615f1623a65c45a9f08a5351c3ebeeb733438d3fd93e5a507db2bfe

test:
  secret_key_base: efc30e1694923fd106d3452aba9096e74d66e80e186b625e6bbb5bb4dd020bed432af9bfb07c009ce1941974501b425bc9d3bca3dca0b0ae933d1d91950091f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
